### ISSUE TITLE
Can't connect to jupyterhub

### ISSUE THREAD

**Issue by lifetooeasy** [microsoft/vscode-jupyter-hub#45]
## Environment data

-   VS Code version: 1.85.1
-   Jupyter Extension version (available under the Extensions sidebar): Switch to Pre-Release Version
-   Python Extension version (available under the Extensions sidebar): Switch to Pre-Release Version
-   OS (Windows | Mac | Linux distro) and version: Ubuntu 22
-   Python and/or Anaconda version: 3.10
-   Type of virtual environment used (N/A | venv | virtualenv | conda | ...): conda
-   Jupyter server running: Remote 

## Expected behaviour

Connect jupyterhub session via vscode jupyterhub extension.

## Actual behaviour

Invalid username or password.

## Steps to reproduce:

[**NOTE**: Self-contained, minimal reproducing code samples are **extremely** helpful and will expedite addressing your issue]

As described in the doc.

## Logs

<details>

<summary>Output for <code>Jupyter</code> in the <code>Output</code> panel (<code>View</code>→<code>Output</code>, change the drop-down the upper-right of the <code>Output</code> panel to <code>Jupyter</code>)
</summary>

<p>

```
12:17:34.165 [error] Failed to start the Jupyter Server Error: Failed to fetch user info, Internal Server Error (500) with message  {"status": 500, "message": "error"}
    > at startServer (/.vscode/extensions/ms-toolsai.jupyter-hub-2023.10.1003492320/dist/extension.node.js:64252:9)
```

</p>
</details>

**Comment by DonJayamanne** [comment]
Thanks for filing this issue and sorry you are running into this issue.
Are you still running into this issue?
What version of Jupyter Hub do you have installed?
Can you verify you can log into Jupyter hub via the browser?

**Comment by lifetooeasy** [comment]
@DonJayamanne Unfortunately, I still have this issue I am running jupyterhub 1.5.0 and yes I can log in to jupyterhub.

**Comment by lifetooeasy** [comment]
@DonJayamanne I am running version `2.3.1` of jupyterhub now and still have same issue, do you don't think that the new versions of vscode or `vscode-jupyter-hub` are the cause of this issue?

**Comment by lifetooeasy** [comment]
could be related to #39 ?

**Comment by quantum-byte** [comment]
@life
Because i was looking into a [similiar issue](https://github.com/microsoft/vscode-jupyter/issues/15439) just now.

Are there any special characters in the Jupyterhub username or what does your Jupyterhub user specific instance url look like ?

**Comment by DonJayamanne** [comment]
@quantum-byte @lifetooeasy 
Please can you install this version of Jupyter Hub extension, & let me know if this works for you.

* Download the file
* Extract the zip file
* Open VS Code and select the command `Install from VSIX`
* Select the extracted *.vsix file
* When prompted, reload VS Code
* Test again

[ms-toolsai-jupyter-hub-insiders.vsix.zip](https://github.com/microsoft/vscode-jupyter/files/14781970/ms-toolsai-jupyter-hub-insiders.vsix.zip)

**Comment by lifetooeasy** [comment]
```
11:07:53.330 [debug] 
11:07:53.455 [debug] Error: Failed to get user info, Internal Server Error (500) with message  {"status": 500, "message": "Internal Server Error"}
    > at getUserInfo (/home/bendoukha/.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:66986:9)
11:07:53.641 [debug] 
11:07:53.641 [debug] 
11:07:53.644 [debug] 
11:07:53.886 [error] Failed to get user info Error: Failed to get user info, Forbidden (403) with message  {"status": 403, `message": "Forbidden"}
    > at getUserInfo (/.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:66986:9)
11:07:53.887 [debug] 
11:07:54.024 [debug] Error: Failed to get user info, Internal Server Error (500) with message  {"status": 500, "message": "Internal Server Error"}
    > at getUserInfo (vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:66986:9)
11:07:54.239 [debug] 
11:07:54.240 [error] Failed to get the user Jupyter Url TypeError: Cannot read properties of undefined (reading 'length')
    > at getUserInfo (/.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:66979:77)
11:07:55.625 [error] SessionManager cannot enumerate kernelSpecs. Specs undefined.
11:07:55.629 [error] Uri verification error Error: Failed to enumeration kernel Specs
    > at /.vscode/extensions/ms-toolsai.jupyter-hub-2024.4.100/dist/extension.node.js:67150:21
    ```

**Comment by liudaolunboluo** [comment]
I'm having the same problem, I reinstalled using visx and still have the same problem, my username has no special characters and I'm pretty sure I can log in in my browser!

**Comment by DonJayamanne** [comment]
Please can you
* Uninstall JupyterHub extension
* Download the attached file
* Extract this file
* Open VS Code and select the command `Install from VSIX`
* Select the above extracted VSIX
* Enable logging (debug logging)
* When prompted to reload VS Code, please do so
* Try to replicate the issue once again
* Capture all the logs from the `JupyterHub` output panel
* Share the logs



[ms-toolsai-jupyter-hub-insiders.vsix.zip](https://github.com/user-attachments/files/16423209/ms-toolsai-jupyter-hub-insiders.vsix.zip)


Screenshot for enabling logging


![Image](https://github.com/user-attachments/assets/f6515fff-304f-4eff-bc88-139f9f2ce4b2)


To get to the logs, please open the bottom output panel (use the command `Outupt: Focus Output View`)
& then select `JupyterHub`


![Image](https://github.com/user-attachments/assets/309a13d9-14ea-4e70-b617-4385556e1064)

**Comment by lifetooeasy** [comment]
@DonJayamanne vscode can connect to remote server and list the available remote kernels.
When I click on one of them the kernel is enabled BUT when I try to execute a cell I got this:

```
10:21:49.318 [info] Starting Kernel xxx for 'Untitled-1.ipynb' (disableUI=false)
10:21:49.876 [error] Failed to change kernel, re-throwing Error: '_xsrf' argument missing from POST
    > at new n (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:98:4480)
    > originalException = Error: '_xsrf' argument missing from POST
10:21:49.884 [warn] Error occurred while trying to start the kernel, options.disableUI=false Error: Failed to connect to the remote Jupyter Server. Verify the server is running and reachable. ('_xsrf' argument missing from POST).
    > at Qc.create (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:285:2808)
    > serverProviderHandle = [object Object]
    > originalError = Error: '_xsrf' argument missing from POST
10:21:49.888 [warn] Kernel Error, context = start Error: Failed to connect to the remote Jupyter Server. Verify the server is running and reachable. ('_xsrf' argument missing from POST).
    > at Qc.create (/home/~/.vscode/extensions/ms-toolsai.jupyter-2024.6.0-linux-x64/dist/extension.node.js:285:2808)
    > serverProviderHandle = [object Object]
    > originalError = Error: '_xsrf' argument missing from POST

```

**Comment by DonJayamanne** [comment]
How have you started Jupyter hub? Is this locally installed? 

If so please can you share the details of the versions of Jupyter hub and other packages

**Comment by lifetooeasy** [comment]
I am trying to connect to a remote jupyterhub not locally. It runs version **4.1.5** und jupyterlab **4.2.2**.

**Comment by DonJayamanne** [comment]
Found the reason

**(Below, notes for personal use)**

* The docker container uses `jupyterhub-singleuser` to start the Jupyter Lab server
`customizes that program to change (approximately) one thing: authenticate requests with JupyterHub.`

See here https://jupyterhub.readthedocs.io/en/latest/explanation/singleuser.html

`By default, jupyter-server uses its own cookie to authenticate. If that cookie is not present, the server redirects you a login page and asks you to enter a password or token.`

As a result of this, the WebSocket also needs the headers (in particular the `Cookie`)
Without this, the websocket request is deemed un-authenticated and a 403 error is returned, thus the websocket handshake fails.

**Comment by DonJayamanne** [comment]
@lifetooeasy 
Please try installing this VSIX, should fix the issue


[ms-toolsai-jupyter-hub-insiders.vsix (1).zip](https://github.com/user-attachments/files/16436835/ms-toolsai-jupyter-hub-insiders.vsix.1.zip)

**Comment by DonJayamanne** [comment]
@lifetooeasy 
I think i have a better understanding of the issue now.
Do you have any idea how the remote JupyterHub server has been configured.

* Do you just need a user name & password to authenticate against that server when using a regular browser (outside VS Code)?
    * Is this using OAuth or some other authentication mechanism?
* What details are you providing when you try to connect to this from within VS Code?

**Comment by lifetooeasy** [comment]
@DonJayamanne 

* outside vscode I am using username/password to authenticate 
* I am providing the URL of the jupyterhub server + username + token

**Comment by dorsegal** [comment]
I had the same issue `Error: '_xsrf' argument missing from POST`.  took this fix https://github.com/microsoft/vscode-jupyter-hub/pull/65 and now I have another error.

`Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffe`

**Comment by DonJayamanne** [comment]
@dorsegal  you are running into the issue https://github.com/microsoft/vscode-jupyter-hub/issues/64

**Comment by dorsegal** [comment]
I tried the work around but I have the same result. 

Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer

**Comment by Yefee** [comment]
> I tried the work around but I have the same result.
> 
> Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer

This is something I also encountered. 

Although I have found a workaround, it is still painful to repeat the process every time. 
Follow these steps: 1) Open JupyterHub in your browser and terminate the current kernel. 2) Return to VS Code and click "Restart" at the top of the notebook. 3) Run the notebook again and you've bypassed this error from now on.
For every notebook, you have to repeat this process 😫.

**Comment by nitzanvolman** [comment]
We are having this issue as well, 
and i can confirm this workaround works. pretty annoying.

**Comment by nitzanvolman** [comment]
we have this issue as well, 
I can confirm this workaround works (pretty annoying) 

Cursor Version: 0.40.4
VSCode Version: 1.91.1

JupyterHub Extension Version:  v2024.5.1002432242

JupyterLab Version: Version 4.0.12

**Comment by DonJayamanne** [comment]
HI everyone, I'm sorry you have been running into this issue.
A fix has been shipped, however you'll need to install VS Code insiders and the latest pre-release version of the Jupyter extension.
Please could you install that and let me know how that goes.

**Comment by jaymc-arg** [comment]
I't working for me, thank you so much for your work @DonJayamanne

**Comment by Yefee** [comment]
Thanks for update @DonJayamanne. The error persists in VS code insider + Jupyter v2024.10.2024101001 (pre-release) + Jupyter Hub v2024.10.1002831100 (pre-release)

```09:15:15.419 [info] Starting Kernel () for '~/work/projects/SST-bias/test_vs_code.ipynb' (disableUI=true)
09:15:17.773 [error] Error in websocket [Error: Server sent no subprotocol
	at ClientRequest.<anonymous> (/glade/u/home/~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-hub-2024.10.1002831100/dist/extension.node.js:6406:11)
	at ClientRequest.emit (node:events:519:28)
	at TLSSocket.socketOnData (node:_http_client:591:11)
	at TLSSocket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)]
09:15:18.006 [info] Started session for kernel connectToLiveRemoteKernel:65d91870-622a-4418-93a3-313ac3192dfe
09:15:18.011 [info] Kernel successfully started
09:15:18.141 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.142 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.143 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.144 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.145 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.165 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.177 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.178 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.179 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.182 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.184 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.185 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.186 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.187 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.188 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.196 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.202 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.203 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.203 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
09:15:18.204 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
```

**Comment by DonJayamanne** [comment]
@Yefee Please can you try `2024.10.2024101501`

Going to close this for now, as the pre-release should fix this.
If not, please do ping here and i'll look into this.

**Comment by Yefee** [comment]
@DonJayamanne thanks for the following up. 

I tried `2024.10.2024101501` and `2024.11.2024102401`. Same error persists.

```
15:09:34.129 [info] Starting Kernel () for '~/work/projects/SST-bias/test_dataspell.ipynb' (disableUI=true)
15:09:34.634 [error] Error in websocket [Error: Server sent no subprotocol
	at ClientRequest.<anonymous> (/glade/u/home/~/.vscode-server-insiders/extensions/ms-toolsai.jupyter-hub-2024.10.1002831100/dist/extension.node.js:6406:11)
	at ClientRequest.emit (node:events:519:28)
	at TLSSocket.socketOnData (node:_http_client:591:11)
	at TLSSocket.emit (node:events:519:28)
	at addChunk (node:internal/streams/readable:559:12)
	at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)
	at Readable.push (node:internal/streams/readable:390:5)
	at TLSWrap.onStreamRead (node:internal/stream_base_commons:191:23)]
15:09:34.868 [info] Started session for kernel connectToLiveRemoteKernel:c7abf360-82bd-44f1-a830-e38153c22ee4
15:09:34.875 [info] Kernel successfully started
15:09:35.139 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.140 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.141 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.142 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.143 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.153 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer
15:09:35.160 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an ArrayBuffer

```

**Comment by hermaneyd** [comment]
@DonJayamanne hi,

I also tried 2024.10.1002831100 for Windows from Marketplace. Same error persists:
```
 [error] Exception while handling messages: TypeError: First argument to DataView constructor must be an `ArrayBuffer`
```

**Comment by DonJayamanne** [comment]
Closing in favour of https://github.com/microsoft/vscode-jupyter-hub/issues/74
